on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Install Mono
        run: sudo apt-get install -y mono-runtime

      - name: Restore dependencies
        run: nuget restore SwimRankings
          
      - name: Build solution and generate NuGet package
        run: dotnet pack SwimRankings/SwimRankings.Api -c Release -o out

      - name: Push generated package to GitHub registry
        run: nuget push out/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}}
